package(default_visibility = ["//visibility:public"])

py_library(
    name = "mobilenet_v2",
    srcs = [
        "imagenet_utils.py",
        "mobilenet_v2.py",
    ],
    srcs_version = "PY2AND3",
    deps = ["//mobilenet/layers"],
)
